Contents
 - 데이터 구조 Series, DataFrame
 - 인덱스, 생성, 선택, 추가, 변경, 삭제, 전치
 - 파이썬 자료형과 양방향 변환

#### 판다스
Pandas는 파이썬에서 데이터 분석 및 조작을 위한 강력하고 유연한 오픈 소스 라이브러리. Series와 DataFrame 같은 고수준의 데이터 구조를 제공하여, 복잡한 데이터 조작을 직관적이고 효율적으로 수행할 수 있게 해다.

[Pandas의 주요 역할과 기능]

* DataFrame과 Series: 2차원 테이블과 1차원 배열 형태의 데이터 구조를 제공
* 데이터 처리: 결측값 처리, 데이터 정제, 필터링, 병합, 연결 및 변환 등을 위한 다양한 기능을 제공
* 데이터 분석: 기술통계, 그룹화, 시계열 분석 등 복잡한 분석 작업을 제공
* 입출력 기능: CSV, Excel, SQL, JSON 등 다양한 파일 형식의 데이터를 읽고 쓸 수 있는 기능을 제공
* 시각화 지원: 매트플롯립과 연동하여 데이터 시각화가 가능하도록 제공
* 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
* 시리즈 인덱스는 데이터 값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)

In [ ]:
#시리즈 클래스 만들기
#pandas 불러오기 (pd)
import pandas as pd

# k:v 구조를 갖는 딕셔너리를 만들고 변수 dict_data에 저장
dict_data = {'a':1,'b':2,'c':3}

sr = pd.Series(dict_data)
print(sr)
print(type(sr))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
#리스트를 시리즈로 변환

list_data = ['2019-07-02',3.14,'ABC',100,True]
#sr = pd.Series(list_data.index=list('abcde'))
sr = pd.Series(list_data)
print(sr,type(sr))

0    2019-07-02
1          3.14
2           ABC
3           100
4          True
dtype: object <class 'pandas.core.series.Series'>

In [ ]:
#인덱스 및 값
idx = sr.index
val = sr.values
print(idx)
print(val)

RangeIndex(start=0, stop=5, step=1)
['2019-07-02' 3.14 'ABC' 100 True]

In [ ]:
#튜플을 시리즈로 변환
tup_data = ('kebin','2019-07-02','남',True)
#sr1 = pd.Series(tup_data)
sr = pd.Series(tup_data,index = ['이름','생년월일','성별','학생여부'])
print(sr)

이름           kebin
생년월일    2019-07-02
성별               남
학생여부          True
dtype: object

In [ ]:
sr = [1,2,3,4,5]
sr[1:3]

[2, 3]

In [ ]:
#인덱싱
#import warnings
#warnings,filterwarnings('ignore')
print(sr[0])
print(sr['이름'])
print(sr[[1,2]]) # 판다스 시리즈에서 위치 기반 인덱싱을 사용해서 여러 요소를 선택 가능
#print(sr[1,2]) #파이썬의 기본 인덱싱 방식으로 sr[1]과 같은 형태를 사용

1

TypeError: list indices must be integers or slices, not str

In [ ]:
 배열
import numpy as np

s1 = np.arange(11,21,2)
print(s1, type(s1))
s2 = pd.Series(s1, index=list('abcde'))
print(s2, type(s2))

NameError: name '배열' is not defined

Q.배열을 생성 후 시리즈로 변환하여 아래와 같이 출력하세요

In [ ]:
data = np.arange(1000, 5000, 1000)
state = ['Califonia','Ohio','Oregon','Texas']
#print(data,type(data))
obj=pd.Series(data, index=state)
obj.name='population'
obj.index.name = 'state'
print(obj, type(obj))

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int64 <class 'pandas.core.series.Series'>

None과 np.nan의 차이점
- None은 파이썬의 내장형 객체로 주로 객체형 데이터에서 사용
- np.nan은 부동소수점으로 취급되며 주로 숫자형 데이터에서 사용
- 연산 시 np.nan은 NaN 결과를 반환하는 반면 None은 TypeError를 발생시킨다

In [ ]:
obj.Califonia = np.nan
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [ ]:
null_mask = obj.isnull()
null_mask

state
Califonia     True
Ohio         False
Oregon       False
Texas        False
Name: population, dtype: bool

In [ ]:
not_null_mask = obj.notnull()
not_null_mask

state
Califonia    False
Ohio          True
Oregon        True
Texas         True
Name: population, dtype: bool

In [ ]:
filled_series = obj.fillna(0)
filled_series

state
Califonia       0.0
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [ ]:
obj.Califonia = np.nan
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [ ]:
obj.isnull().sum()

1

In [ ]:
dropped_series = obj.dropna()
dropped_series

state
Ohio      2000.0
Oregon    3000.0
Texas     4000.0
Name: population, dtype: float64

In [ ]:
dropped_series.isnull().sum()

0

In [ ]:
print(s2, type(s2))

NameError: name 's2' is not defined

In [ ]:
# Series -> List
list_from_series = s2.tolist()
list_from_series

NameError: name 's2' is not defined

In [ ]:
dict_from_series = s2.to_dict()
dict_from_series

NameError: name 's2' is not defined

In [ ]:
df_from_series = s2.to_frame(name='Value')
df_from_series

NameError: name 's2' is not defined

Q. 아래 시리즈에서 null값을 2개 입력 후 그 값을 0으로 대체 후 null값 여부를 확인한 후 출력하세요.

In [ ]:
import pandas as pd
import numpy as np

# 1. Series 생성
s = pd.Series([5, 15, 25, 35, 45], index=['x', 'y', 'z', 'w', 'v'])

s['y'] = np.nan
s['w'] = np.nan

print("null 갯수:", s.isna().sum(), '\n')

s_filled = s.fillna(0)
print("null 갯수:", s_filled.isna().sum(), '\n')
print(s_filled)

null 갯수: 2

null 갯수: 0

x     5.0
y     0.0
z    25.0
w     0.0
v    45.0
dtype: float64

Q. 주어진 리스트 [1, 2, 3, 4, 5]를 Pandas Series로 변환하고, 각 원소에 10을 더한 Series를 출력하세요.

In [ ]:
import pandas as pd

# 주어진 리스트
data_list = [1, 2, 3, 4, 5]

series = pd.Series(data_list)

series_plus_10 = series + 10

print("Original Series:")
print(series)
print("\nSeries after adding 10 to each element:")
print(series_plus_10)

Original Series:
0    1
1    2
2    3
3    4
4    5
dtype: int64

Series after adding 10 to each element:
0    11
1    12
2    13
3    14
4    15
dtype: int64

Q. Series [10, 20, 30, 40, 50]를 생성하고 인덱스를 ['a', 'b', 'c', 'd', 'e']로 설정하세요. 인덱스를 기준으로 Series를 정렬한 결과를 출력하세요.

In [ ]:
import pandas as pd

# 주여진 데이터와 인덱스
data = [10, 20, 30, 40, 50]
index = ['a', 'c', 'b', 'd', 'e']

# Pandas Series 생성
series = pd.Series(data, index=index)

# 인덱스를 기준으로 정렬
series.sorted = series.sort_index()

# 결과출력
print(series)
print(series.sorted)

Q. Series ['a':1, 'b':2, 'c':3, 'd':4, 'e':5]에서 인덱스 'b', 'd'에 해당하는 원소를 선택하여 출력하세요.

In [ ]:
import pandas as pd

# 주어진 데이터와 인덱스
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']

series = pd.Series(data, index=index)

selected_elements = series[['b','d']]

print(selected_elements)

b    2
d    4
dtype: int64

#### 데이터프레임
* 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래.
* 데이터프레임의 열은 각각 시리즈 개체.
* 시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를
  기준으로 줄지어 결합된 2차원 벡터 또는 행렬.
* 선형대수학에서 열 벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
* 행 벡터(1 x m 행렬)은 m원소들의 단일 행 행렬.
* 리스트, 딕셔너리, ndarray 등 다양한 데이터로부터 생성
* 반대로 리스트, 딕셔너리, ndarray 등으로 변환될 수 있음

In [ ]:
# 베일을 데이터프레임으로 변환
np.random.seed(0)
data = np.random.randint(100,120,size=(3,3))
print(data, type(data))

df=pd.DataFrame(data,index=['d1','d2','d3'],
                columns = ['pd','sales','inv'])
print(df, type(df))

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>
     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118 <class 'pandas.core.frame.DataFrame'>

In [ ]:
print(df.pd, type(df.pd))

d1    112
d2    103
d3    109
Name: pd, dtype: int64 <class 'pandas.core.series.Series'>

In [ ]:
df = pd.DataFrame(data, columns = ['pd','sales','inv'])
df

    pd  sales  inv
0  112    115  100
1  103    103  107
2  109    119  118

#### Pandas의 iloc와 loc 메서드
DataFrame과 Series에서 데이터의 특정 위치나 라벨에 접근하기 위한 중요한 도구이며 두 메서드는 각각 고유한 용도를 가지고 있다.

- iloc (Integer Location)
  - 정수 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 특정 위치에 있는 데이터를 선택할 때 사용.
  - 슬라이싱 지원: Python 리스트와 유사하게 슬라이싱을 지원.
  - 양 끝점 포함하지 않음: 슬라이싱 시 끝점은 포함하지 않는다.
- loc (Label Location)
  - 라벨 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 라벨 이름을 사용하여 데이터에 접근.
  - 슬라이싱 지원: 라벨을 사용하여 슬라이싱을 지원.
  - 끝점 포함: 슬라이싱 시 끝점을 포함.

In [ ]:
import pandas as pd

# 데이터프레임 생성
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}

df = pd.DataFrame(data)
print(df, '\n')
# 첫번째 행 두번째 열의 값 선택
print(df. iloc[0,1])

print(df. iloc[0:2,0:2])

   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

5
   A  B
0  1  5
1  2  6

In [ ]:
import pandas as pd

# 데이터프레임 생성
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data, index=['a','b','c','d'])
print(df, '\n')

print(df. loc['a','B'])

print(df. loc['a':'b','A':'B'])

   A  B   C
a  1  5   9
b  2  6  10
c  3  7  11
d  4  8  12

5
   A  B
a  1  5
b  2  6

In [ ]:
# 베일을 데이터프레임으로 변환
np.random.seed(0)
data = np.random.randint(100,120,size=(3,3))
print(data, type(data))

df=pd.DataFrame(data,index=['d1','d2','d3'],
                columns = ['pd','sales','inv'])
print(df, type(df))

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>
     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118 <class 'pandas.core.frame.DataFrame'>

In [ ]:
print(df. iloc[1],'\n')
print(df. loc['d2'])

In [ ]:
print(df. iloc[1,:],'\n')
print(df. loc['d2',:])

In [ ]:
print(df. iloc[1,2])
print(df. loc['d2','inv'])

In [ ]:
df.loc['d3'] = 0
df

In [ ]:
df.loc['d4'] = 0
df

In [ ]:
df.loc[:,'profit'] = 10
df

In [ ]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20), '\n') # min max 사이 float 리턴
print(random.randrange(10), '\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [ ]:
import numpy as np
print(np.random.randint(6), '\n') # 0 ~ 5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1 ~ 19까지 정수인 난수 1개
print(np.random.randint(10, size=10), '\n') # 0 ~ 9까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n') # 10 ~ 19까지 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5))) # 10 ~ 19까지 정수인 난수로 3행 5열 배열 생성

In [ ]:
#id, gender, age, region
import numpy as np
import pandas as pd
id = np.arange(1,1001)
i1 = pd.Series(id)
gender = np.random.randint(2,size=1000)
g1 = pd.Series(gender)
age = np.random.randint(1,101,size=1000)
a1 = pd.Series(age)
region = np.random.randint(1,11,size=1000)
r1 = pd.Series(region)
#print(i1,g1,a1,r1)
df = pd.concat([i1,g1,a1,r1],axis=1)
df.rename(columns={0:'id', 1:'gender', 2:'age', 3:'region'},inplace=True)
df.head()

   id  gender  age  region
0   1       0   11      10
1   2       1   68      10
2   3       0    7       7
3   4       0   92      10
4   5       0  100      10

In [ ]:
df.drop([0], axis=0, inplace=True)
df.head()

- at은 라벨 기반 인덱싱을 사용 단일 값을 접근할 때 loc 접근자 보다 빠르다.
- 여러 값을 동시에 접근하려면 loc 접근자를 사용

In [ ]:
df.loc[5,'id']

In [ ]:
df.at[5,'id']

In [ ]:
df1=df.drop(df.at[5,'id'])
df1.head(7)

In [ ]:
# df1=df[:]
df1=df.copy()
df1.head()
# df1.tail(3)

   id  gender  age  region
0   1       0   11      10
1   2       1   68      10
2   3       0    7       7
3   4       0   92      10
4   5       0  100      10

In [ ]:
a = np.random.randint(1, 5, size=(10, 5))
print(a, type(a))

In [ ]:
# 2차원 리스트를 데이터프레임으로 변환
list1 = a.tolist()
# print(list1, type(list1))

df1=pd.DataFrame(list1, columns=['c1','c2','c3','c4','c5'])

print(df1.head())

In [ ]:
ar=df1.values
print(ar, type(ar))
print()
li = ar.tolist()
print(li, type(li))
print()
dict=df1.to_dict('list')
print(dict, type(dict))

결측치 처리 방법

In [1]:
import pandas as pd
import numpy as np

# 예제 데이터프레임 생성
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, np.nan, 5],
    'C': [1, np.nan, np.nan, 4, 5],
    'D': [1, 2, 3, 4, 5]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
     A    B    C  D
0  1.0  NaN  1.0  1
1  2.0  2.0  NaN  2
2  NaN  3.0  NaN  3
3  4.0  NaN  4.0  4
4  5.0  5.0  5.0  5

In [2]:
df_filled_zero = df.fillna(0)
print(df_filled_zero)

     A    B    C  D
0  1.0  0.0  1.0  1
1  2.0  2.0  0.0  2
2  0.0  3.0  0.0  3
3  4.0  0.0  4.0  4
4  5.0  5.0  5.0  5

In [4]:
# null 값을 각 열의 평균값으로 채우기
df_filled_mean = df.apply(lambda x: x.fillna(x.mean()), axis=0)
print(df_filled_mean)

     A         B         C  D
0  1.0  3.333333  1.000000  1
1  2.0  2.000000  3.333333  2
2  3.0  3.000000  3.333333  3
3  4.0  3.333333  4.000000  4
4  5.0  5.000000  5.000000  5

In [5]:
# null 값을 각 열의 중간값으로 채우기
df_filled_median = df.apply(lambda x: x.fillna(x.median()), axis=0)
print(df_filled_median)

     A    B    C  D
0  1.0  3.0  1.0  1
1  2.0  2.0  4.0  2
2  3.0  3.0  4.0  3
3  4.0  3.0  4.0  4
4  5.0  5.0  5.0  5

In [6]:
# null 값이 포함된 행 삭제하기
df_droped_rows = df.dropna()
print(df_droped_rows)

     A    B    C  D
4  5.0  5.0  5.0  5

In [7]:
# null 값이 포함된 열 삭제하기
df_droped_columns = df.dropna(axis=1)
print(df_droped_columns)

   D
0  1
1  2
2  3
3  4
4  5

In [8]:
#  앞 또는 뒤의 값으로 채우기 (forward fill, backward fill)
df_ffill = df.fillna(method='ffill')
print(df_ffill,'\n')

df_bfill = df.fillna(method='bfill')
print(df_bfill)

     A    B    C  D
0  1.0  NaN  1.0  1
1  2.0  2.0  1.0  2
2  2.0  3.0  1.0  3
3  4.0  3.0  4.0  4
4  5.0  5.0  5.0  5

     A    B    C  D
0  1.0  2.0  1.0  1
1  2.0  2.0  4.0  2
2  4.0  3.0  4.0  3
3  4.0  5.0  4.0  4
4  5.0  5.0  5.0  5

In [9]:
#  replace 메서드를 사용하여 null 값을 다른 값으로 대체
import pandas as pd
import numpy as np

# 예제 데이터프레임 생성
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, np.nan, 5],
    'C': [1, np.nan, np.nan, 4, 5],
    'D': [1, 2, 3, 4, 5]
}

df=pd.DataFrame(data)
print(df)

     A    B    C  D
0  1.0  NaN  1.0  1
1  2.0  2.0  NaN  2
2  NaN  3.0  NaN  3
3  4.0  NaN  4.0  4
4  5.0  5.0  5.0  5

In [10]:
# replace를 사용하여 null 값을 0으로 대체
df_replace_zero = df.replace(np.nan,0)
print(df_replace_zero)
# replace를 사용하여 null 특정값 으로 대체   (예:-1)
df_replace_zero = df.replace(np.nan,-1)
print(df_replace_zero)

     A    B    C  D
0  1.0  0.0  1.0  1
1  2.0  2.0  0.0  2
2  0.0  3.0  0.0  3
3  4.0  0.0  4.0  4
4  5.0  5.0  5.0  5
     A    B    C  D
0  1.0 -1.0  1.0  1
1  2.0  2.0 -1.0  2
2 -1.0  3.0 -1.0  3
3  4.0 -1.0  4.0  4
4  5.0  5.0  5.0  5

Task1_0527. 4개의 Series를 결합하여 데이터프레임을 생성하여 출력하세요.
- 출력한 데이터프레임에서 추출하고 싶은 5개의 데이터를 인덱싱하여 출력
- null값을 3개 추가
- null값의 개수를 확인하고 삭제
- 2개의 데이터를 수정
- 1개의 행을 삭제

In [ ]:
import numpy as np
import pandas as pd

# 데이터프레임 생성
id = np.arange(1, 1001)
i1 = pd.Series(id)
gender = np.random.randint(2, size=1000)
g1 = pd.Series(gender)
age = np.random.randint(1, 101, size=1000)
a1 = pd.Series(age)
region = np.random.randint(1, 11, size=1000)
r1 = pd.Series(region)
df = pd.concat([i1, g1, a1, r1], axis=1)
df.rename(columns={0: 'id', 1: 'gender', 2: 'age', 3: 'region'}, inplace=True)

In [ ]:
# 데이터프레임에서 추출하고 싶은 5개의 데이터를 인덱싱하여 출력
print(df.iloc[[0, 1, 2, 3, 4]])

In [ ]:
# null값을 3개 추가
df.loc[0, 'age'] = np.nan
df.loc[1, 'gender'] = np.nan
df.loc[2, 'region'] = np.nan

In [ ]:
# null값의 개수를 확인하고 삭제
null_counts = df.isnull().sum()
print( null_counts,'\n')
df.dropna(inplace=True)
print(df.head(7))

In [ ]:
# 2개의 데이터를 수정
df.loc[3, 'age'] = 50
df.loc[4, 'region'] = 5

In [ ]:
#  1개의 행을 삭제
df.drop(index=5, inplace=True)

In [ ]:
# 최종 데이터프레임 출력
print(df.head(7))

Task2_0527. 학생별 성적 데이터셋으로 의미있게 데이터 셋을 수정하세요.(아래 사항 반영)
- S1 ~ S10은 평균 점수를 기준으로 1등급에서 10등급이고 등급간 점수 차는 5점
- 결시자가 국어 3명, 수학 2명 있음
- 영어, 수학의 평균 점수가 국어 대비 5점 낮음

In [ ]:
import pandas as pd
import numpy as np
df = np.random.randint(1,5,size=(10,5))
df=pd.DataFrame(df,index=['s1','s2','s3','s4','s5','s6','s7','s8','s9','s10'],
               columns=['국어','영어','수학','과학','사회'])
df

In [ ]:
# 등급 간 점수 차는 5점
for i in range(10):
  df.iloc[i]=90-i*5
df

In [ ]:
# 영어 수하그이 평균 점수가 국어 대비 5점 낮음
for i in range(10):
  df.iloc[i,1:3] = df.iloc[i,0] - 5
df

In [ ]:
# 결시자가 국어 3명 수학 2명 있음
a= df.copy()
a.iloc[7:,0] = np.nan
a.iloc[8:,2] = np.nan
a

Task3_0527. df1에서 결측값 처리 후 딕셔너리, 리스트로 변환하여 출력하세요.

In [ ]:
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Math": [85, np.nan, 88, 90, 76],
    "English": [92, 85, 89, np.nan, 80],
    "Science": [78, 90, 95, 85, 89],
    "History": [88, 92, 85, 91, np.nan]
})
df1

In [ ]:
df1.info()

In [ ]:
df1.columns

In [ ]:
# 숫자 열에 대해 결측값을 각 열의 평균값으로 대체
df2 = df1.copy()
columns = ['Math','English','Science','History']
for column in columns:
  df2[column].fillna(df2[column].mean(),inplace=True)
df2

In [ ]:
# df1 데이터프레임에서 숫자형 데이터 타입을 가진 열들만 선택
df2 = df1.copy()
for column in df2.select_dtypes(include=[np.number]).columns:
    df2[column].fillna(df2[column].mean(), inplace=True)
df2

In [ ]:
# 배열로 변환
array1=df2.to_numpy()
print(array1, type(array1),'\n')

# 딕셔너리로 변환
dict1=df2.to_dict('list')
print(dict1,'\n')

# 리스트로 변환
list1=df2.values.tolist()
print(list1)

Task4_0527. df2에서 아래와 같이 데이터 필터링 및 정렬 후 배열, 딕셔너리, 리스트로 변환하여 출력하세요.
- Math 점수가 80 이상인 학생만 선택
- English 점수를 기준으로 내림차순 정렬

In [ ]:
df2 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Math": [85, 79, 88, 90, 76],
    "English": [92, 85, 89, 93, 80],
    "Science": [78, 90, 95, 85, 89],
    "History": [88, 92, 85, 91, 84]
})

In [ ]:
# 필터링 :Math 점수가 80 이상인 학생만 선택
df2_filltered = df2[df2['Math']>=80]

# 정렬:English 점수를 기준으로 내림차순 정렬
df2_sorted = df2_filltered.sort_values(by='English', ascending=False)

# 결과 출력
print(df2_sorted)

In [ ]:
# 배열로 변환
array2 = df2_sorted.to_numpy()
print(array2, type(array2),'\n')

# 딕셔너리로 변환
dict2 = df2_sorted.to_dict('list')
print(dict2,'\n')

# 리스트로 변환
list2 = df2_sorted.values.tolist()
print(list2)

Task5_0527. df3에서 각 학생의 평균 점수 계산 후 배열, 딕셔너리, 리스트로 변환하여 출력하세요.

In [ ]:
df3 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice", "Bob", "Charlie", "David", "Eve"],
    "Subject": ["Math", "Math", "Math", "Math", "Math", "English", "English", "English", "English", "English"],
    "Score": [85, 79, 88, 90, 76, 92, 85, 89, 93, 80]
})
df3

In [ ]:
df3.pivot_table(index='Name',columns='Subject',values='Score',aggfunc='mean')

In [ ]:
df3_pivot=df3.pivot_table(index='Name',columns='Subject',values='Score',aggfunc='mean').reset_index()
df3_pivot.columns.name = None
# 결과출력
print(df3_pivot)

In [ ]:
# 배열로 변환
array3 = df3_pivot.to_numpy()
print(array3, type(array3),'\n')

# 딕셔너리로 변환
dict3 = df3_pivot.to_dict('list')
print(dict3,'\n')

# 리스트로 변환
list3 = df3_pivot.values.tolist()
print(list3)

Task6_0527. df4에서 특정 열의 데이터 타입을 변환한 후 변환된 타입을 확인하세요.

In [ ]:
df4 = pd.DataFrame({
    'A': ['1', '2', '3', '4'],
    'B': ['5.1', '6.2', '7.3', '8.4'],
    'C': ['2021-01-01', '2021-02-01', '2021-03-01', '2021-04-01']
})

In [ ]:
# 'A' 열을 정수형(int)으로 변환
df4['A']=df4['A'].astype(int)
# 'B' 열을 부동 소수점(float)으로 변환
df4['B']=df4['B'].astype(float)
# 'C' 열을 datetime 형식으로 변환
df4['C']=pd.to_datetime(df4['C'])
# 데이터 타입 확인
print(df4.dtypes)

Task7_0527. df5에서 나이가 25 이상인 행을 출력하세요.

In [ ]:
df5 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
})

In [ ]:
# 조건에 따라 데이터프레임의 부분집합 선택(나이가 25이상인 행)
subset = df5[df5['Age']>=25]
print("\n나이가 25 이상인 행:\n \n",subset)

In [ ]:
df5

In [ ]:
df5[["Name",'City']]

In [ ]:
# file 생성
import pandas as pd
file_data = pd.DataFrame({
    'col1': [1, 2, 3, 4, 5, 6],
    'col2': ['A', 'A', 'B', 'B', 'C', 'C']
})

print(file_data)

In [ ]:
file_data.to_csv('file_data.csv', index=None)

In [ ]:
!ls

In [ ]:
file_data = pd.read_csv('file_data.csv')
print(file_data,'\n', type(file_data))

In [ ]:
df_1 = pd.DataFrame({
    'col1':np.array([1,2,3]),
    'col2':np.array(['A','B','C'])
})
df_2 = pd.DataFrame({
    'col1':np.array([4,5,6]),
    'col2':np.array(['D','E','F'])
})
print(df_1)
print()
print(df_2)

In [ ]:
# Q.df1과 df2를 행방향과 열방향으로 병합하여 출력하세요
df_3=pd.concat([df_1,df_2],axis=1)
df_4=pd.concat([df_1,df_2])
print(df_3)
print()
print(df_4)

In [ ]:
df_4.iloc[:,1]

In [ ]:
df_4['col2']

In [ ]:
df_4.iloc[1]

In [ ]:
# 데이터프레임 생성(8행 5열)
import numpy as np
import pandas as pd

np.random.seed(3)
data = np.random.randint(50,100,size=(8,5))

df = pd.DataFrame(data, columns=list('abcde'))
df

In [ ]:
# 열이름과 행이름 변경
columns={'a':'국어','b':'영어','c':'수학','d':'과학','e':'음악'}
index={0:'a',1:'b',2:'c',3:'d',4:'e',5:'f',6:'g',7:'h'}
df.rename(columns=columns,index=index,inplace=True)
df

In [ ]:
# 데이터프레임 생성
import numpy as np
import pandas as pd
np.random.seed(0)

data = np.random.randint(80,100,size=(5,5))
df = pd.DataFrame(data, columns=list('abcde'))
df

In [ ]:
df1=df.copy()
df1

In [ ]:
# df1['index'] = list['가나다라마']
# df1
df1['index'] = ['가', '나', '다', '라', '마']
df1

In [ ]:
df2=df1.set_index("index")
df2

In [ ]:
df21=df2.drop('e', axis=1)
df21

In [ ]:
df3=df2.reset_index()
df3

In [ ]:
df22 = df3.set_index('index')
df22

In [ ]:
df22.index.name=None
df22

In [ ]:
# 딕셔서리를 정의
dict_data = {'a':[1,2,3,4,5], 'b':[4,5,6,7,8], 'c':[7,8,9,10,11], 'd':[10,11,12,13,14], 'e':[13,14,15,16,17]}

# 딕셔서리를 데이터프레임으로 변환. 인덱스를 [r0, r1, r2]로 지정
df = pd.DataFrame(dict_data, index=['r0','r1','r2','r3','r4'])
df

In [ ]:
# Q.df에 r5,r6 2개의 행을 추가하고 값은 0을 적용하여 출력하세요
df.loc['r5']=0
df.loc['r6']=0
df

In [ ]:
new_index=['r0','r1','r2','r3','r4','r5','r6','r7','r8']
df5=df.reindex(new_index,fill_value=0)
df5

In [ ]:
df1=df5.reindex(new_index)
df1

In [ ]:
df1=df5.drop(df5.index[5:9])
df1

In [ ]:
# 인덱스 기준 정렬
df1_s=df1.sort_index(ascending=False)
df1_s

In [ ]:
df1_c=df1.sort_values(by='c',ascending=False)
df1_c

In [ ]:
# 전치
# df1_t=df1.franspose()
df1_t = df1.T
df1_t

Q. df1으로 데이터프레임을 생성한 후 set_index를 사용하여 ID를 인덱스 설정한 데이터프레임을 출력하세요.

In [ ]:
df1 = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
})

In [ ]:
df1.set_index('ID', inplace=True)
df1

        Name  Age
ID
101    Alice   24
102      Bob   27
103  Charlie   22
104    David   32

Q. df2에 대해서 다음을 수행하세요.
- set_index를 사용하여 인덱스를 설정.
- reset_index를 사용하여 인덱스를 리셋.

In [ ]:
df2 = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
})

In [ ]:
df2.set_index('ID', inplace=True)
print("인덱스 설정 후:\n", df2)
df2.reset_index(inplace=True)
print("\n인덱스 리셋 후:\n", df2)

인덱스 설정 후:
         Name  Age
ID
101    Alice   24
102      Bob   27
103  Charlie   22
104    David   32

인덱스 리셋 후:
     ID     Name  Age
0  101    Alice   24
1  102      Bob   27
2  103  Charlie   22
3  104    David   32

Q. df3에 대해서 reindex를 사용하여 인덱스를 변경하여 출력하세요.

In [ ]:
df3 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
}, index=[101, 102, 103, 104])

In [ ]:
# 새로운 인덱스 정의
new_index = [201, 202, 203, 204]

# reindex를 사용하여 인덱스 변경
df3_reindexed = df3.reindex(new_index)

# 출력
print(df3_reindexed)

    Name  Age
201  NaN  NaN
202  NaN  NaN
203  NaN  NaN
204  NaN  NaN

Q. df4에 대해서 reindex를 사용하여 인덱스를 변경하고 결측치를 0으로 채운 데이터프레임을 출력하세요.

In [ ]:
df4 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 27, 22]
}, index=[0, 1, 2])

print("기존 인덱스:\n", df4)

기존 인덱스:
       Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22

In [ ]:
new_index = [0, 1, 2, 3]

# reindex를 사용하여 인덱스 변경 및 결측치를 0으로 채우기
df4_reindexed = df4.reindex(new_index, fill_value=0)

# 출력
print("새로운 인덱스 및 결측치 0으로 채워진 DataFrame:\n", df4_reindexed)

새로운 인덱스 및 결측치 0으로 채워진 DataFrame:
       Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
3        0    0

Q. df5에서 reindex를 사용하여 특정 날짜 범위로 인덱스를 재설정하여 출력하세요.

In [ ]:
dates = pd.date_range('2024-01-01', periods=4, freq='D')
df5 = pd.DataFrame({
    'Value': [10, 20, 30, 40]
}, index=dates)

In [ ]:
# 새로운 인덱스 범위 정의
new_index = pd.date_range('2024-01-05', periods=6, freq='D')

# reindex를 사용하여 인덱스 변경
df5_reindexed = df5.reindex(new_index)

# 출력
print(df5_reindexed)

            Value
2024-01-05    NaN
2024-01-06    NaN
2024-01-07    NaN
2024-01-08    NaN
2024-01-09    NaN
2024-01-10    NaN

Q. 데이터프레임 df6를 전치하고, 전치된 데이터프레임을 정리하여 연도별 판매량 데이터를 제품별로 나열하여 출력하세요.

In [ ]:
data = {
    'Year': ['2020', '2021', '2022'],
    'Product_A': [500, 600, 700],
    'Product_B': [400, 500, 600],
    'Product_C': [300, 400, 500]
}
df6 = pd.DataFrame(data)
df6

   Year  Product_A  Product_B  Product_C
0  2020        500        400        300
1  2021        600        500        400
2  2022        700        600        500

In [ ]:
df6_transposed = df6.set_index('Year').T

# 출력
print(df6_transposed)

Year       2020  2021  2022
Product_A   500   600   700
Product_B   400   500   600
Product_C   300   400   500